spring:
  # DB 연결
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ####테스트중 번호 임의 변경#### 3307, ptmanDB,
    url: jdbc:mysql://localhost:3306/ptmanDB?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password
  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect